site_name: BOLC Class 25-012 Documentation

repo_url: https://github.com/alvinye9/bolc_25-012.github.io

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.sections
    - navigation.footer
    - content.tabs.link
    - navigation.expand
    - navigation.top
    - lightbox
  icon: 
    repo: fontawesome/brands/github
  logo: Icons/1-145.png
  favicon: Icons/1-145.png


markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Event Calendar: index.md

  - Major Events Past/Upcoming:
      - Flight Physical: Main/Flight_Physical/index.md
      - OP83 [28 MAR - Complete]: Main/OP83/index.md
      - ACFT [01 APR - Complete]: Main/ACFT/index.md
      - Memorandum [DUE 14 APR]: Main/Memo/index.md
      - PRT Schedule [14 APR - 17 APR]: Main/PT/index.md
      - PRT Schedule [21 APR - 24 APR]: Main/PT2/index.md
      - PRT Schedule [28 APR - 2 May]: Main/PT3/index.md
      

  - Admin:
      - Flight School Expectations: Main/Expectations/index.md
      - Range/Land-Nav Packing List: Main/Range/index.md
      - Ft. Novosel Blue Book: Main/BlueBook/index.md
      - Leave/Pass Policy: Main/LeavePass/index.md

  - Misc:
    - License : DeveloperGuide/License/index.md
    - Contact : DeveloperGuide/Contact/index.md
