site_name: BOLC Class 25-012 Documentation

repo_url: https://github.com/alvinye9/bolc_25-012.github.io

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.sections
    - navigation.footer
    - content.tabs.link
    - navigation.expand
    - navigation.top
    - lightbox
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Event Calendar: index.md

  - Major Events:
      - Flight Physical [26-27 MAR]: Main/Flight_Physical/index.md
      - OP83 [28 MAR]: Main/OP83/index.md

  # - Major Events Planner: Main/Planner/index.md

  - Misc:
    - License : DeveloperGuide/License/index.md
    - Contact : DeveloperGuide/Contact/index.md
